version: '3.9'

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        volumes:
            - E:/Docker/mysql_home:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        networks: 
            - net
    postgres:
      container_name: postgres
      image: postgres
      restart: always
      volumes:
        - E:/Docker/pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: root
      ports:
        - 5432:5432
      networks: 
        - net  

networks:
  net:
    driver: bridge